### ISSUE TITLE
Possible flag / name configuration

### ISSUE THREAD

**Issue by iamqqv** [scherersoftware/cake-language-switcher#4]
We want to hide the language names in the dropdown toggle button. Currently there's no way to achieve that. Reason for that is that 
```
<?= $this->Html->image('LanguageSwitcher.flags/' . $imageMapping[I18n::locale()] . '.png', [
            'style' => 'height: 17px; margin-right: 5px;'
        ]); ?>
```
has an inline style with a margin. Even if we hide the language name via CSS the margin still persists.
It would be nice if displaying the name in the toggle button would be configurable or some other way to achieve our intention.

**Comment by robertscherer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ticket 1](https://trello.com/c/uyvJ7EK9/6-ticket-1)

**Comment by cleptric** [comment]
Will be cleaned up in v2
